### ISSUE TITLE
Пополнение неизвестных событий 10 11 12 14 62

### ISSUE THREAD

**Issue by TheDeaX-Lab** [danyadev/longpoll-doc#3]
#: Сброс флагов диалога $peer_id.
#: Соответствует операции (PEER_FLAGS &= ~$flags).
#: Только для диалогов сообществ.
PEER_FLAGS_RESET = 10
Структура: [peer_id, flags]

    
#: Замена флагов диалога $peer_id.
#: Соответствует операции (PEER_FLAGS:= $flags).
#: Только для диалогов сообществ.
PEER_FLAGS_REPLACE = 11
Структура: [peer_id, flags]
   
 #: Установка флагов диалога $peer_id.
#: Соответствует операции (PEER_FLAGS|= $flags).
#: Только для диалогов сообществ.
PEER_FLAGS_SET = 12
Структура: [peer_id, flags]
    
#: Восстановление недавно удаленных сообщений в диалоге $peer_id с
 #: идентификаторами вплоть до $local_id.
PEER_RESTORE_ALL = 14
Структура: [peer_id, local_id]

#: Пользователь $user_id набирает текст в беседе $chat_id.
USER_TYPING_IN_CHAT = 62
Структура: [user_id, chat_id]

Таблица флагов для peer_flags
| Число | Информация |
| --- | --- |
| 1 | Важный диалог |
| 2 | Неотвеченный диалог |

**Comment by danyadev** [comment]
Нет смысла брать подобную информацию из официальной документации.

События 10 и 12 приходят не только для диалогов сообществ и делают они совсем не то, что описано. Я в принципе знаю что делают эти события, но напишу про них чуть позже.

Событие 11 я не встречал, возможно оно и вправду для диалогов сообществ, но у меня документация по __User__ LongPoll, поэтому не буду лезть в лп сообществ.

Событие 14 я когда-то даже сам пытался вызвать, но оно просто не приходит. Повторюсь, не стоит верить документации, она довольно устаревшая и содержит подобные события, которые уже давным давно были удалены.

Событие 62 также устаревшее, его заменяет события 63 (набор текста) и 64 (запись голосового сообщения).
